### ISSUE TITLE
Unifi-Controller issues

### ISSUE THREAD

**Issue by HeroNextDoor** [Plexmation/plexmation-docker#1]
halo mem,

kan jew pleaz feeks da unifi controller. Eish eat as nawt whorking.

Fank yew

**Comment by sjdaniel10** [comment]
Hi Sir,
Please make sure you populate the IP address in the following field:
![image](https://user-images.githubusercontent.com/26638567/83451764-cefcb780-a457-11ea-965e-b948c776f424.png)
